# Generated by Django 6.1 on 2026-09-19

import django.db.models.deletion
from django.db import migrations, models


def copy_categories(apps, schema_editor):
    ProductCategory = apps.get_model("products", "Category")
    Category = apps.get_model("categorie", "Category")
    Product = apps.get_model("products", "Product")

    mapping = {}
    for old in ProductCategory.objects.all().iterator():
        new, _ = Category.objects.get_or_create(name=old.name)
        mapping[old.id] = new.id

    for product in Product.objects.all().iterator():
        new_id = mapping.get(product.category_id)
        if new_id is not None:
            product.category_id = new_id
            product.save(update_fields=["category"])


class Migration(migrations.Migration):

    dependencies = [
        ("categorie", "0001_initial"),
        ("products", "0003_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="categorie.category",
            ),
        ),
        migrations.RunPython(copy_categories, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="Category",
        ),
    ]