# Generated by Django 6.1 on 2026-09-19

from django.contrib.auth.hashers import make_password
from django.db import migrations

HASH_PREFIXES = ("pbkdf2_", "argon2", "bcrypt", "scrypt", "sha1$")


def hash_plaintext_passwords(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all().iterator():
        if not user.password.startswith(HASH_PREFIXES):
            user.password = make_password(user.password)
            user.save(update_fields=["password"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_phone_adresse"),
    ]

    operations = [
        migrations.RunPython(hash_plaintext_passwords, noop),
    ]