# Generated by Django 6.1 on 2026-09-20 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0001_initial'),
        ('users', '0003_hash_plaintext_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='categorie.category'),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validée'), ('suspended', 'Suspendue')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'En attente'), ('suspended', 'Suspendue')], default='active', max_length=20),
        ),
    ]
