# Generated by Django 6.1 on 2026-09-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('shipped', 'Expédiée'), ('completed', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=20),
        ),
    ]
