# Generated by Django 6.1 on 2026-09-20 13:05

from django.db import migrations


def migrate_confirmed_to_shipped(apps, schema_editor):
    Order = apps.get_model("commande", "Order")
    Order.objects.filter(status="confirmed").update(status="shipped")


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_alter_order_status'),
    ]

    operations = [
        migrations.RunPython(migrate_confirmed_to_shipped, migrations.RunPython.noop),
    ]