# Generated by Django 6.1 on 2026-09-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order', 'Commande'), ('product', 'Produit'), ('system', 'Système'), ('promotion', 'Promotion'), ('shop', 'Boutique'), ('alert', 'Alerte'), ('message', 'Message')], default='system', max_length=20),
        ),
    ]
