# Generated by Django 6.1 on 2026-09-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favoris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='favorite',
            name='status',
            field=models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Masqué')], default='visible', max_length=20),
        ),
    ]
