# Generated by Django 6.1.1 on 2026-09-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('owner_name', models.CharField(max_length=150)),
                ('industry', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=20)),
                ('slogan', models.CharField(blank=True, default='', max_length=200)),
                ('facebook', models.URLField(blank=True, default='', max_length=300)),
                ('instagram', models.URLField(blank=True, default='', max_length=300)),
                ('tiktok', models.URLField(blank=True, default='', max_length=300)),
                ('website', models.URLField(blank=True, default='', max_length=300)),
                ('province', models.CharField(max_length=60)),
                ('commune', models.CharField(max_length=60)),
                ('neighborhood', models.CharField(max_length=100)),
                ('other_neighborhood', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validée'), ('rejected', 'Rejetée'), ('suspended', 'Suspendue')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Boutique',
                'verbose_name_plural': 'Boutiques',
                'ordering': ['-created_at'],
            },
        ),
    ]
