# Generated by Django 6.1 on 2026-09-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='BUJA MARKET', max_length=100)),
                ('support_email', models.EmailField(default='support@buja.market', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('default_language', models.CharField(default='fr', max_length=10)),
                ('currency', models.CharField(default='BIF', max_length=10)),
                ('moderation', models.JSONField(blank=True, default=dict)),
                ('notifications', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Paramètres de la plateforme',
                'verbose_name_plural': 'Paramètres de la plateforme',
            },
        ),
    ]
